# Generated by Django 5.1.7 on 2025-03-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriverInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=40)),
                ('birthday', models.DateField()),
                ('drivers_license_number', models.CharField(max_length=20, unique=True)),
                ('drivers_license_issue_date', models.DateField(blank=True, null=True)),
                ('drivers_license_expiry_date', models.DateField(blank=True, null=True)),
                ('employment_date', models.DateField(blank=True, null=True)),
                ('email', models.CharField(max_length=40, unique=True)),
            ],
        ),
    ]
