# Generated by Django 5.1.7 on 2025-03-15 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refuel',
            fields=[
                ('refuel_id', models.AutoField(primary_key=True, serialize=False)),
                ('mileage_at_refuel', models.IntegerField()),
                ('fuel_liters', models.FloatField()),
                ('refuel_date', models.DateTimeField(auto_now_add=True)),
                ('driver_id', models.ForeignKey(db_column='driver_id', on_delete=django.db.models.deletion.CASCADE, to='drivers.driverinfo')),
                ('vehicle_vin', models.ForeignKey(db_column='vehicle_vin', on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicleinfo')),
            ],
        ),
    ]
