# Generated by Django 5.1.7 on 2025-03-15 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleInfo',
            fields=[
                ('VIN', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('vehicle_make_model', models.CharField(max_length=50)),
                ('body_colour', models.CharField(max_length=20)),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('registration_cert_number', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
