# Generated by Django 5.1.7 on 2025-03-15 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('from_location', models.CharField(max_length=255)),
                ('to_location', models.CharField(max_length=255)),
                ('start_mileage', models.IntegerField(blank=True, default=None, null=True)),
                ('end_mileage', models.IntegerField(blank=True, default=None, null=True)),
                ('start_time', models.TimeField(blank=True, default=None, null=True)),
                ('end_time', models.TimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField()),
                ('driver_id', models.ForeignKey(db_column='driver_id', on_delete=django.db.models.deletion.CASCADE, to='drivers.driverinfo')),
                ('vehicle_vin', models.ForeignKey(db_column='vehicle_vin', on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicleinfo')),
            ],
        ),
    ]
